### PR TITLE
feat: add columnar db

### PR DESCRIPTION
**Pull request by riderx**
Please go the the `Preview` tab and select the appropriate sub-template:

* [Default](?expand=1&template=default.md)
* [Extension Upgrade](?expand=1&template=extension_upgrade.md)

### CODE REVIEW

**Comment by olirice** [comment]
thank you for opening and the PR looks good

The bar for adding new extensions to the platform is very high as it's a big commitment from us to maintain them indefinitely if the current authors become unavailable. In this case we the extension is fairly new (< 18 months old) and the platform already supports a comparable extension through TimescaleDB's column store. For those reasons, I'm going to close this for now. If we see a big uptick in requests for hydra we can revisit in the future

**Comment by riderx** [comment]
Thanks @olirice for the quick reply.

I understand your concern, to give some context, Hydra is a company running cloud DB like Supabase.
It's a fork of an older project, [citus](https://github.com/citusdata/citus) **7 years old**.

Hydra isolated the extension before citus took a direction of Distributed DB, I could have used columnar from citus.

In my point of view (as Supabase cloud client) TimescaleDB is not doing the job, the license prevents any interesting use of TimescaleDB.
https://docs.timescale.com/about/latest/timescaledb-editions/
No compression, no Continuous aggregates, no retention policy, no Actions and automation.

So by adding an alternative, i'm resolving my current issue in Supabase Cloud.

So I would be grateful if you could consider this a bit further.

Columnar is "Next generation of cstore_fdw", using latest best practices of Postgres.

This could open many use cases in analytics for cloud user who cannot use TimescaleDB

I'm open to any alternative I found hydra was more close in philosophy that citus to supabase.

A good alternative could be to use https://pgxman.com/ for extension since it's made for install extension and has hydra listed.

**Comment by olirice** [comment]
thanks for the links, very interesting read

I think long term we are likely to revisit column storage in addition to timescale. Before we make any decisions we'll need to do an internal review of options that includes:
- features
- performance
- alignment with our products' direction
- supportability by our tech team
- supportability by our support team (we handle support for our extensions as well as the supabase platform)

I'll make sure we include hydra in that comparison when we circle back to tackle to it, but its not something we can add for right now

**Comment by riderx** [comment]
@olirice okay, i will keep using clickhouse until i can put back my analytics into Supabase.
Thank for considering it !

**Pull request closed without merging**
