### PR TITLE
Use GitHub action runner instead

### PR DESCRIPTION
**Pull request by sweatybridge**
## What kind of change does this PR introduce?

Bug fix, feature, docs update, ...

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Review by darora — COMMENTED** [review]
Have we tested this out? Whats the reason we're changing this? Iirc we switched away to internal workers because the builds never finished on the GH hosted workers (CPU constraints or w/e)

**Comment by sweatybridge** [comment]
Yes this is the run from my own fork using ubuntu-latest runner https://github.com/sweatybridge/postgres/actions/runs/3856067392/jobs/6571831699. The run built the image in 30 mins but failed to push because I didn't give it the token.

**Comment by sweatybridge** [comment]
I think with ccache, the runner doesn't need as much cpu as before.

**Comment by sweatybridge** [comment]
https://github.com/sweatybridge/postgres/actions/runs/3860186275/jobs/6580353194 here's a successful run without push. 

I suspect we are missing some configuration for our self hosted x86 runner. May be the docker credentials were not mounted as secrets?

**Comment by darora** [comment]
> I think with ccache, the runner doesn't need as much cpu as before.

Wouldn't that cause things to fail again if a PR changed enough things that the cache couldn't be re-used?

I'm happy to approve this if you'd like, but it doesn't sound like we understand the root cause for the failures, given things were building OK three weeks ago.

**Review by darora — APPROVED** [review]
approving, if you prefer unblocking with this PR

**Comment by sweatybridge** [comment]
Thanks, I will check with @pcnc next week. May be the runner had an old version of ccache image in its docker cache.

**Pull request merged**
