### PR TITLE
fix: pg_net grants post pg-upgrade

### PR DESCRIPTION
**Pull request by pcnc**
Context: https://supabase.slack.com/archives/C01D6TWFFFW/p1710240426372859

### CODE REVIEW

**Review by tomashley — APPROVED** [review]

**Comment by la289** [comment]
We just ran into this issue again so I don't think this is resolved

**Comment by mulyoved** [comment]
Also, Just happened again now

**Comment by tmountain** [comment]
Happening to us right now.

**Comment by patrickshiel** [comment]
Seeing a similar issue right now too. Cannot `update` any table that has an associated Database WebHook.

**Comment by stockiesnz** [comment]
I'm also having this issue.

**Comment by GohWaiJian** [comment]
having this issue
permission denied for table http_request_queue

**Comment by eugenc** [comment]
I get ERROR:  42501: permission denied to set parameter "cron.use_background_workers"

**Pull request merged**
