### PR TITLE
Revert "Upgrade pgroonga to v13"

### PR DESCRIPTION
**Pull request by pashkinelfe**
Reverts supabase/postgres#619

### CODE REVIEW

**Review by darora — APPROVED** [review]

**Comment by Code-Hex** [comment]
@pashkinelfe Why was it reverted?

**Comment by pashkinelfe** [comment]
@Code-Hex it was temporarily reverted as before merging we need to run some tests to ensure it doesn't break anything. It will be committed a bit later.

**Comment by Code-Hex** [comment]
@pashkinelfe I see. I'm looking forward!

**Comment by devhandler** [comment]
@pashkinelfe wondering if the test is done and can we now enable pgroonga 3.0?

cc @Code-Hex

**Comment by darora** [comment]
Already released as part of https://github.com/supabase/postgres/pull/669

New (or upgraded) projects are already on pgroonga 3.0

**Comment by devhandler** [comment]
thank you!

**Pull request merged**
