### PR TITLE
fix: Reduce ansible playbook build time

### PR DESCRIPTION
**Pull request by Lakshmipathi**
Signed-off-by: Lakshmipathi <lakshmi@supabase.io>

### CODE REVIEW

**Comment by Lakshmipathi** [comment]
Seems like using `async` we reduce ami build time. During testing found around 40% performance gain.  Still need to verify few things more making this as PR.

**Comment by Lakshmipathi** [comment]
Playbook run time reduced from  [42mins](https://github.com/supabase/postgres/pull/329#issuecomment-1283603690) to 24mins.

    amazon-ebssurrogate.source: Playbook run took 0 days, 0 hours, 24 minutes, 31 seconds
    amazon-ebssurrogate.source: Monday 24 October 2022  04:15:49 +0000 (0:00:00.378)       0:24:31.021 ********
    amazon-ebssurrogate.source: ===============================================================================
    amazon-ebssurrogate.source: postgis - build SFCGAL ------------------------------------------------ 263.29s
    amazon-ebssurrogate.source: install cargo-pgx ----------------------------------------------------- 236.26s
    amazon-ebssurrogate.source: libsodium - build ------------------------------------------------------ 71.69s
    amazon-ebssurrogate.source: pgRouting - build ------------------------------------------------------ 66.41s
    amazon-ebssurrogate.source: Postgres - build ------------------------------------------------------- 58.08s
    amazon-ebssurrogate.source: wal-g - build and install ---------------------------------------------- 50.94s
    amazon-ebssurrogate.source: timescaledb - build ---------------------------------------------------- 45.55s
    amazon-ebssurrogate.source: pljava - build --------------------------------------------------------- 43.86s
    amazon-ebssurrogate.source: libsodium - configure -------------------------------------------------- 43.77s
    amazon-ebssurrogate.source: wal-g - deps ----------------------------------------------------------- 38.13s
    amazon-ebssurrogate.source: postgis - build -------------------------------------------------------- 28.00s
    amazon-ebssurrogate.source: Postgres - configure --------------------------------------------------- 17.42s
    amazon-ebssurrogate.source: PgBouncer - build ------------------------------------------------------ 14.22s
    amazon-ebssurrogate.source: install rust/cargo ----------------------------------------------------- 13.91s
    amazon-ebssurrogate.source: plpgsql_check - install ------------------------------------------------ 12.33s
    amazon-ebssurrogate.source: pg_graphql - build libgraphqlparser ------------------------------------ 11.35s
    amazon-ebssurrogate.source: timescaledb - download & install dependencies -------------------------- 10.55s
    amazon-ebssurrogate.source: rum - build ------------------------------------------------------------- 9.87s
    amazon-ebssurrogate.source: PgBouncer - configure --------------------------------------------------- 9.85s
    amazon-ebssurrogate.source: Remove build dependencies ----------------------------------------------- 9.54s
    amazon-ebssurrogate.source: Monday 24 October 2022  04:15:49 +0000 (0:00:00.380)       0:24:31.023 ********
    amazon-ebssurrogate.source: ===============================================================================
    amazon-ebssurrogate.source: make ------------------------------------------------------------------ 743.42s
    amazon-ebssurrogate.source: shell ----------------------------------------------------------------- 421.03s
    amazon-ebssurrogate.source: apt ------------------------------------------------------------------- 128.78s
    amazon-ebssurrogate.source: unarchive -------------------------------------------------------------- 46.49s
    amazon-ebssurrogate.source: get_url ---------------------------------------------------------------- 31.08s
    amazon-ebssurrogate.source: git -------------------------------------------------------------------- 26.12s
    amazon-ebssurrogate.source: file ------------------------------------------------------------------- 21.25s
    amazon-ebssurrogate.source: template --------------------------------------------------------------- 12.77s
    amazon-ebssurrogate.source: copy ------------------------------------------------------------------- 11.90s
    amazon-ebssurrogate.source: systemd ----------------------------------------------------------------- 7.79s
    amazon-ebssurrogate.source: ufw --------------------------------------------------------------------- 6.24s
    amazon-ebssurrogate.source: lineinfile -------------------------------------------------------------- 4.22s
    amazon-ebssurrogate.source: user -------------------------------------------------------------------- 3.05s
    amazon-ebssurrogate.source: replace ----------------------------------------------------------------- 1.69s
    amazon-ebssurrogate.source: gather_facts ------------------------------------------------------------ 1.12s
    amazon-ebssurrogate.source: async_status ------------------------------------------------------------ 0.81s
    amazon-ebssurrogate.source: find -------------------------------------------------------------------- 0.70s
    amazon-ebssurrogate.source: group ------------------------------------------------------------------- 0.69s
    amazon-ebssurrogate.source: pam_limits -------------------------------------------------------------- 0.59s
    amazon-ebssurrogate.source: set_fact ---------------------------------------------------------------- 0.54s
    amazon-ebssurrogate.source: community.general.snap -------------------------------------------------- 0.42s
    amazon-ebssurrogate.source: ansible.builtin.stat ---------------------------------------------------- 0.26s
    amazon-ebssurrogate.source: ansible.builtin.fail ---------------------------------------------------- 0.03s
    amazon-ebssurrogate.source: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    amazon-ebssurrogate.source: total ---------------------------------------------------------------- 1470.99s

**Comment by sweatybridge** [comment]
Question: do we need to recompile every extension in every ami build even if its version didn't change?

Docker can cache each build command in an image layer. Not sure if something similar is available for ansible.

Another possibility is to use conan.io for managing build dependencies. Not really sure if it works with Postgres dependencies though.

**Comment by Lakshmipathi** [comment]
This commented out [ccache](https://github.com/supabase/postgres/blob/develop/ebssurrogate/scripts/surrogate-bootstrap.sh#L299) step should handle that.  Now that we have pgtap tests during build process itself, this should allow to capture issues before image creation, let me enable this step and check. 

One thing is: We just need to make sure pgtap tests are strong enough to catch any mis-configured items from the ami. 

>let me enable this step and check.

hmm, looks like it stopped working. Need more time to investigate this, until then we can go with `async` way.

**Review by dragarcia — APPROVED** [review]
do remember to bump the version to trigger a build.

**Pull request merged**
